language: node_js
node_js:
 - '--lts'
 - '10.5.0'
 - '10.0.0'
 - '8.9.3'
 - '8.0.0'
 - '7.0.0'
cache:
  directories:
    - node_modules
branch: master
script:
  - npm run test:simple
  - npm run test
  - npm run gendoc:buildin
